# Generated by Django 4.2.1 on 2023-08-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesdislikes',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likesCount', to='network.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(default='Mon 21 Aug 2023, 02:42PM', max_length=50),
        ),
    ]
