# Generated by Django 4.2.1 on 2023-08-23 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_likesdislikes_post_alter_posts_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='likesdislikes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likedPosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likesdislikes',
            name='dislikes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='likesdislikes',
            name='likes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(default='Wed 23 Aug 2023, 05:36PM', max_length=50),
        ),
    ]
