# Generated by Django 4.2.1 on 2023-08-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_likesdislikes_user_alter_likesdislikes_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislikesCounta',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='likesCounta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(default='Wed 23 Aug 2023, 11:27PM', max_length=50),
        ),
    ]
