# Generated by Django 4.2.1 on 2023-08-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_posts_dislikescounta_posts_likescounta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='dislikesCounta',
            new_name='dislikesCountForDOM',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='likesCounta',
            new_name='likesCountForDOM',
        ),
    ]
