# Generated by Django 4.2.1 on 2023-08-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_dislikescounta_posts_dislikescountfordom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(default='Wed 23 Aug 2023, 11:28PM', max_length=50),
        ),
    ]
