# Generated by Django 4.2.1 on 2023-08-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_posts_shoulddislikebuttonvisibledom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='ShouldDisLikeButtonVisibleDOM',
            new_name='ShouldDisLikeButtonDisabledDOM',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='ShouldLikeButtonVisibleDOM',
            new_name='ShouldLikeButtonDisabledDOM',
        ),
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.CharField(default='Thu 24 Aug 2023, 07:52PM', max_length=50),
        ),
    ]
